### ISSUE TITLE
Cannot find module 'internal/fs' on Node.js 7.5.0

### ISSUE THREAD

**Issue by yakovkhalinsky** [apiaryio/drafter-npm#11]
```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "drafter" "--save"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yakov/git/drakov/npm-debug.log
```

Installation was attempted on Mac OS Sierra.

After switching back to Node.js 6.9.5 installation was successful

**Comment by spahicharis** [comment]
For me solution was to delete **@angular/cli folder** from C:\Users\****\AppData\Roaming\npm\node_modules and to install it globaly again with `npm install -g @angular/cli`

node: v7.3.0
npm: v4.0.5

**Comment by kylef** [comment]
Looks like this was resoled, please let us know if this is still a problem for you.
