### ISSUE TITLE
TypeError on native

### ISSUE THREAD

**Issue by jtwebman** [apiaryio/drafter-npm#12]
I am running node 6.9.1 and when just running a basic example I get the following error: 
```bash
/Users/jt/projects/gamma-docker/src/app/gamma-partner/api-doc/generate.js:15
    drafter.parse(file, options, (parseError, result) => {
            ^

TypeError
    at TypeError (native)
    at fileSystem.readFile (/Users/jt/projects/gamma-docker/src/app/gamma-partner/api-doc/generate.js:15:13)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

Here is the file I am using: 
```javascript
'use strict';

const fileSystem = require('fs');
const path = require('path');
const drafter = require('drafter');

const options = {
  generateSourcemap: true
};

fileSystem.readFile(path.join(__dirname, 'API.apib'), 'utf8', (fileError, file) => {
  if (fileError) {
    console.error(fileError);
  } else {
    drafter.parse(file, options, (parseError, result) => {
      if (parseError) {
        console.error(parseError);
      } else {
        console.log(JSON.stringify(result, null, 2));
      }
    });
  }
});
```

Errors even with the example API blueprint polls: https://github.com/apiaryio/api-blueprint/blob/master/examples/Polls%20API.md

Running drafter version 1.2.0

**Comment by kylef** [comment]
@jtwebman I think the problem may be that the options set is incorrect type. There is `generateSourcemap` which should be `generateSourceMap`. Please try fixing the case for this option and see if that helps.

**Comment by pksunkara** [comment]
@jtwebman Any update on this?

**Comment by mikekoetter** [comment]
The misspelling of `generateSourceMap` was my issue as well, as that is the spelling that is used in the Readme example

**Comment by jtwebman** [comment]
Yep this fixed it for me, sorry for the delay on getting back.
