### ISSUE TITLE
Allow implementation selection via ENV var

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter-npm#3]
As an author of a project depending on this library, I'd like to select underlying implementation by ENV variable regardless my computer setup to see possible differences in occurring issues. E.g.

```
$ DRAFTER=JS npm install
```

vs.

```
$ DRAFTER=CPP npm install
```

---

Note: Are there any existing workarounds how to force one version or another to test out stuff?

**Comment by honzajavorek** [comment]
Found a workardound - just install regularly and then go and delete all `protagonist` folders in your `node_modules` tree to test with JS version of Drafter only.

**Comment by kylef** [comment]
Yes, I originally considered adding an environment variable switch but I wanted to keep the code simple instead of adding potentially unnessecery features. But if there is demand it totally makes sense to add this.

**Comment by honzajavorek** [comment]
Let's wait with this. In https://github.com/apiaryio/dredd/pull/573 I later realised the issues I have are due to https://github.com/apiaryio/dredd/issues/574 and not because of the protagonist/drafter change. Thus, my request for this feature lost its use case for now. The two libraries seem to behave in the same way.

I'll test against both for a while anyway as Dredd seems to be the first consumer ever, but I can achieve that by deleting protagonist folders. I probably won't keep the practice for long and will test only against drafter.js after some period.

**Comment by honzajavorek** [comment]
Just found out another workaround how to force Drafter NPM to use Drafter.js: have a virtualenv where `python` means Python 3 :trollface:

**Comment by kylef** [comment]
@honzajavorek Is this still needed? You can use `npm install --no-optional` to disable Protagonist during installation.

**Comment by honzajavorek** [comment]
That's [exactly what I do](https://github.com/apiaryio/dredd-transactions/blob/50666b1ec645e53cc6bc6f67a58b66061669db66/.travis.yml#L28)
